# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("BufferedStream")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
